theme = "ayu_dark"

[editor]
cursorline = true
continue-comments = false
color-modes = true
# center row, top row, buttom row
jump-label-alphabet = "asdfghjklqwertyuiopbcmnvxz"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.file-picker]
hidden = false

[keys.normal]
C-s = "vsplit"
C-h = "jump_view_left"
C-j = "jump_view_down"
C-k = "jump_view_up"
C-l = "jump_view_right"
C-p = "file_picker"

C-n = "goto_next_diag"
C-m = "goto_prev_diag"

C-f = "global_search"

"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
"^" = "goto_first_nonwhitespace"
G = "goto_file_end"
